### PR TITLE
Server methods - Update

### PR DESCRIPTION
**Pull request by CodeRISHI**
Added/updated a few things:

1.) Added routes for restaurants and users
2.) renamed delete/remove function in user and restaurant controllers
3.) add routes in server.js for /api/
4.) renamed 'liked' to 'likes' in schema/model (need to rename actual file name)

### CODE REVIEW

**Comment by jreidgreer** [comment]
@CodeRISHI What's the purpose of the `removeAll()` methods on the controllers? They take a query from the request, which would seem to mean that they aren't in fact deleting all of the associated models (which is probably good). But if so what makes it different than `removeOne()` that you have on the routes with ids?

**Comment by cehsu** [comment]
@jreidgreer: Thanks for the helpful feedback on Arun's PR, it has implications for the LikesController as well, we could also use an empty object rather than the query, as that will select all entries as well? also, can we envision a use for dropping our tables? or should we simply remove these removeAll functions from all of the controllers? is it standard practice to include them?

**Comment by jreidgreer** [comment]
@cehsu I would agree that if the purpose of the method is to indeed delete all individual documents (what Mongo calls entries) then simply passing in a blank object will do for the query rather than passing in information from the request. I suppose my secondary question is why would we want a method that does this? Since we're presumably not doing tiered authentication, that would mean that any user would have the power to truncate our tables.

**Comment by jreidgreer** [comment]
@cehsu Um, did you update your comment? I swear I didn't see those last few lines. Anyways, yes, that's what I'm wondering too. It would be a security flaw to allow that method to exist.

**Comment by CodeRISHI** [comment]
@jreidgreer The purpose of the `removeAll()` method on the controller is like a 'kill switch' which I suppose is unneeded here. We just worked off of the template for the Hackathon and in that talk, Zach said we would 'never' use it but it's just good to have. He didn't elaborate beyond that and coming to think of it, I suppose we don't need that function here (in this project) either.

If for whatever reason we want to remove all the documents (entries) in the database for users/restaurants, we would have that option but for the scope of this project, I agree that it is rather unnecessary.

EDIT: I will remove that function in both controllers and re-push. So don't merge this PR just yet.

**Comment by jreidgreer** [comment]
@CodeRISHI I agree it definitely would be a convenience method for development, but in production it would be a pretty serious security flaw since any logged in user would be able to send that request.

**Comment by cehsu** [comment]
I see now that this is how Zach built out the functions in the solution code for the hackathon, so i guess either using the query or setting it using and empty object are both ok...?
I guess we're doing away with the removeAll's, so I'll take it out of LikesController also:)

**Comment by CodeRISHI** [comment]
@jreidgreer Yes, that would be quite dangerous to have in production. 

@cehsu Yes, using an empty object would work but not having this function would be the best bet.

**Comment by CodeRISHI** [comment]
Updated to remove the 'removeAll' function from both controllers and routers.

**Pull request merged**
