### PR TITLE
Update - Services, UserControllerSpec, App, RestaurantModel

### PR DESCRIPTION
**Pull request by CodeRISHI**
Added tests for userController, updated services to pass-through 'data' object, and updated routes in app.js to include various templates, and restaurantModel to include URL and eat24 URL fields.

### CODE REVIEW

**Comment by jreidgreer** [comment]
Looks good, but we do need to be more careful about working on the same files. I mentioned yesterday i was working on the Angular routing. We need to decide whether or not the feed is going to be specific to food. Here's how I had this set up:

```
    .when('/feed', {
      templateUrl: 'app/channels/food/feed/feed.html',
      controller: 'FoodFeedController'
    })
```

While in dashboard it makes sense to not be specific to food (presumably dashboard would hold many types of channels). What do you think about this?

**Comment by CodeRISHI** [comment]
Oops. Didn't realize you were working on that file as well.

I think the Dashboard should be set up so that there can be many channels and not just food (although that's all we're doing for this project). That way, the file structure etc. doesn't need to be edited much to add new channels.

If we can do it in such a way that expansion is made easier, that would be best.

**Comment by jreidgreer** [comment]
Right, I agree the Dashboard should be the same. But wasn't each channel going to have its own feed?

**Comment by CodeRISHI** [comment]
Yes, that's true. Each channel with it's own feed but the user Dashboard will have stuff from several feeds  (hypothetically). 

I will make the change to the feed route and push back up right now.

**Pull request merged**
